[frontend]
172.31.30.40 ;COURSE="Ansible for Node-1" # These are called as individual host vars
;172.31.23.59 ;COURSE="Ansible for Node-2"

[catalogue]
172.31.28.172

[user]
172.31.28.173

[cart]
172.31.28.174

; group of groups
[roboshop:children]
frontend
catalogue
user
cart

[local]
localhost

;local group vars
; [local:vars]
; COURSE="Ansible"
; TRAINER="sivakumar"
; DURATION="10HRS"

; [frontend:vars]
; COURSE="Ansible"
; TRAINER="sivakumar"
; DURATION="10HRS"